src/recommender/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^recsystem/', include('recsystem.urls')),
]

src/recsystem/urls.py
from django.conf.urls import url
from . import views

app_name = 'recsystem'
urlpatterns = [

    # /recsystem/
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^studyrec/$', views.studyrec, name='studyrec'),
    url(r'^others/$', views.others, name='others'),
    url(r'^gitrec/$', views.gitrec, name='gitrec'),
    url(r'^allAdvices/$', views.allAdvices, name='allAdvices'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^add_question/$', views.add_question, name='add_question'),
    url(r'^question_form/$', views.question_form, name='question_form'),
    url(r'^add_answer/$', views.add_answer, name='add_answer'),
    url(r'^add_relation/$', views.add_relation, name='add_relation'),
    url(r'^save_relation/$', views.save_relation, name='save_relation'),
    url(r'^add_advice/$', views.add_advice, name='add_advice'),
    url(r'^saveAdvice/(?P<advice_id>[0-9]+)/$', views.saveAdvice, name='saveAdvice'),
    url(r'^save_question/$', views.save_question, name='save_question'),
    url(r'^details/$', views.details, name='details'),
    url(r'^followUp/$', views.followUp, name='followUp'),
    url(r'^getAns/$', views.getAns, name='getAns'),
    url(r'^getSliderAdvice/$', views.getSliderAdvice, name='getSliderAdvice'),
    url(r'^getAdvices/$', views.getAdvices, name='getAdvices'),
    url(r'^saveData/$', views.saveData, name='saveData'),
    url(r'^saveEditedData/$', views.saveEditedData, name='saveEditedData'),
    url(r'^editQuestion/(?P<question_id>[0-9]+)/$', views.editQuestion, name='editQuestion'),
    url(r'^editAdvice/(?P<advice_id>[0-9]+)/$', views.editAdvice, name='editAdvice'),
    url(r'^delete/(?P<question_id>[0-9]+)/$', views.delete, name='delete'),
    url(r'^deleteAll/$', views.deleteAll, name='deleteAll'),

    # /recsystem/123/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail')
]

src/recsystem/models.py
from django.db import models
from django.utils import timezone
#Question table which stores all questions and the followuo questions, each question has differetn answers and are connected
#to the answer table with a foreign key of question table in the answetr table

class Question(models.Model):
    question_title = models.CharField(max_length = 250)
    question_text = models.TextField(max_length = 3000)
    description = models.TextField(max_length = 3000)
    options_type = models.CharField(max_length = 250)
    followUp = models.BooleanField(default=False)
    max = models.CharField(max_length = 250, null=True)
    min = models.CharField(max_length = 250, null=True)
    step = models.CharField(max_length = 250, null=True)

    def __str__(self):
            return self.question_title

class Advice(models.Model):
    advice_label = models.TextField(max_length = 2000)
    advice_text = models.TextField(max_length = 3000)
    time_stamp = models.TextField( default=timezone.now, max_length= 2000)


    def __str__(self):
                return self.advice_label

#answer tabel for the answers and labels that we want to trigger in order to provide some advice in the end.
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length = 250)
    max_val = models.CharField(max_length = 250, null=True)
    min_val = models.CharField(max_length = 250, null=True)
    advices = models.ManyToManyField(Advice)

    def __str__(self):
                return self.answer_text

#cross table for finding the followup questions associated with a particular answer
class FollowUp(models.Model):
    description = models.CharField(max_length = 250)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

src/recsystem/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Question, Advice, Answer, FollowUp
#
# class QuestionForm(forms.ModelForm):
#
#     class Meta:
#         model = Question
#         fields = ['question_title', 'question_text', 'description', 'options_type']
#
#
# class AnswerForm(forms.ModelForm):
#
#     class Meta:
#         model = Answer
#         fields = ['question', 'answer_text', 'answer_label']
#
# class FollowUpForm(forms.ModelForm):
#
#      class Meta:
#          model = FollowUp
#          fields = ['description','question', 'answer']
#
class AdviceForm(forms.ModelForm):

     class Meta:
         model = Advice
         fields = ['advice_label', 'advice_text', 'time_stamp']




class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

src/recsystem/views.py
from django.contrib.auth import authenticate, login
from django.core import serializers
from django.contrib.auth import logout
from django.http import HttpResponse
from django.utils import timezone
from django.http import JsonResponse
import logging
import itertools
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import  AdviceForm
from .models import Question, Answer, FollowUp, Advice
from django.core.exceptions import ObjectDoesNotExist



def index(request):

    return render(request, 'recsystem/index.html')

def studyrec(request):
    try:
        questions = Question.objects.filter(id__in=[175,179,190])
        context = {'questions': questions}
        return render(request, 'recsystem/recommender.html', context)
    except Question.DoesNotExist :
        raise ObjectDoesNotExist


def gitrec(request):
    try:
        questions = Question.objects.filter(id__in=[192,194,195,200,205])
        context = {'questions': questions}
        return render(request, 'recsystem/recommender.html', context)
    except Exception.DoesNotExist:
        raise ObjectDoesNotExist


def others(request):
    questions = Question.objects.filter(followUp=False).exclude(id__in=[175,179,190,192,194,195,200,205])
    context = {'questions': questions}
    return render(request, 'recsystem/recommender.html', context)

def question_form(request):
    questions = Question.objects.all()
    advices = Advice.objects.all()
    context = {
    'allQuestions': questions,
    'advices': advices,
    'allAdvices' : serializers.serialize('json', advices)
    }
    return render(request, 'recsystem/question_form.html', context)

def getAdvices(request):
    advices = Advice.objects.all()
    context = {
    'advices' : serializers.serialize('python', advices)
    }
    return JsonResponse(context, safe=False)

def allAdvices(request):
    advices = Advice.objects.all()
    context = {
    'advices' : advices
    }
    return render(request, 'recsystem/advices.html', context)

def details(request):
    questions = Question.objects.all()
    firstQuestions = Question.objects.filter(followUp=False)
    answers = Answer.objects.all()
    followUps = FollowUp.objects.all()
    advices = Advice.objects.all()
    context = {
    'questions' : questions,
    'answers' : answers,
    'followUps' : followUps,
    'firstQuestions' : firstQuestions,
    'advices' : advices
    }
    return render(request, 'recsystem/questions.html', context)

def editQuestion(request, question_id):
    questions = Question.objects.all()
    question = get_object_or_404(Question, pk=question_id)
    answers = question.answer_set.all()
    allAdvices = Advice.objects.all()

    context = {
    'questions': questions,
    'question': question,
    'answers': answers,
    'allAdvices': allAdvices
    }
    return render(request, 'recsystem/editQuestion.html', context)


def editAdvice(request, advice_id):
    advice = get_object_or_404(Advice, pk=advice_id)
    context = {
    'advice' : advice
    }
    return render(request, 'recsystem/editAdvice.html', context)

def detail(request, question_id):
    return HttpResponse("<h2>Deatils for the question: " + str(question_id) + "</h2>")

def followUp(request):
    fid = request.GET['fid']
    selAns = Answer.objects.get(pk=fid)
    advices = selAns.advices.all()

    try:
        fup = FollowUp.objects.get(answer=fid)
        Question = fup.question
        answers = Question.answer_set.all()
        context = {
        'question': serializers.serialize('python', [fup.question])[0],
        'answers' : serializers.serialize('python', answers),
        'advices' : serializers.serialize('python', advices)
        }

    except FollowUp.DoesNotExist:
        context = {
        'advices' : serializers.serialize('python', advices)
        }

    return JsonResponse(context, safe=False)

def getAns(request):
    qid = request.GET['qid']
    question = Question.objects.get(pk=qid)
    answers =  question.answer_set.all()
    context = {
        'answers' : serializers.serialize('python', answers),
    }

    return JsonResponse(context, safe=False)

def getSliderAdvice(request):
    aid = request.GET['ansId']
    answer = Answer.objects.get(pk=aid)
    advices = answer.advices.all()
    context = {
    'advices' : serializers.serialize('python', advices)
    }
    return JsonResponse(context, safe=False)

def add_question(request):

    form = QuestionForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        question = form.save(commit=False)
        question.save()
        return render(request, 'recsystem/questions.html', {'questions': Question.objects.all(), 'answers': Answer.objects.all(),
        'followUps': FollowUp.objects.all() })
    context = {
        "form": form,
    }
    return render(request, 'recsystem/add_question.html', context)

def add_answer(request):

    form = AnswerForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        answer = form.save(commit=False)
        answer.save()
        return render(request, 'recsystem/questions.html', {'questions': Question.objects.all() })
    context = {
        "form": form,
    }
    return render(request, 'recsystem/add_answer.html', context)

def add_advice(request):

    form = AdviceForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        advice = form.save(commit=False)
        advice.save()
        return render(request, 'recsystem/questions.html', {'questions': Question.objects.all() })
    context = {
        "form": form,
    }
    return render(request, 'recsystem/add_advice.html', context)

def add_relation(request):

    answers = Answer.objects.all()
    questions = Question.objects.all()

    context = {
    'answers' : answers,
    'questions' : questions
    }
    return render(request, 'recsystem/add_relation.html', context)

def save_relation(request):
    f = FollowUp()
    f.answer = Answer.objects.get(pk=request.POST.get('answer'))
    f.question = Question.objects.get(pk=request.POST.get('question'))
    f.save()
    return JsonResponse({'result':'ok'})

def saveAdvice(request, advice_id):

    advice = get_object_or_404(Advice, pk=advice_id)
    advice.advice_label = request.POST['advice_label']
    advice.advice_text = request.POST['advice_text']
    advice.time_stamp = timezone.now()
    advice.save()
    advices = Advice.objects.all()
    context = {
    'advices' : advices
    }
    return render(request, 'recsystem/advices.html', context)


def save_question(request):
    q = Question()
    q.question_title = request.POST['question_title']
    q.question_text = request.POST['question_text']
    q.extra_fields = request.POST['extraFields']
    q.save()
    return render(request, 'recsystem/index.html')

def saveData(request):

    if request.method =='POST' and request.is_ajax():
        q = Question()
        q.question_title = request.POST['queTitle']
        q.question_text = request.POST['queText']
        q.description = request.POST['desc']
        q.options_type = request.POST['optionType']
        q.save()

        if request.POST.get('ansId'):
            try:
                followup = FollowUp()
                q.followUp = True
                q.save()
                followup.description = ""
                followup.answer = Answer.objects.get(pk=request.POST['ansId'])
                followup.question = q
                followup.save()

            except :
                pass

        if request.POST.getlist('anstextArray[]'):
            answers = request.POST.getlist('anstextArray[]')
            if request.POST.getlist('ansAdvicesArray[]'):
                advices = request.POST.getlist('ansAdvicesArray[]')
                zippedList = zip(answers, advices)
                for an, ad in zippedList:
                    adviceList = str(ad)
                    adviceList = adviceList.split(',')
                    answer = Answer()
                    answer.question = q
                    answer.answer_text = an
                    answer.save()
                    for item in adviceList:
                        advice = get_object_or_404(Advice, pk=int(item))
                        answer.advices.add(advice)

                    answer.save()
            else:
                for item in answers:
                    answer = Answer()
                    answer.question = q
                    answer.answer_text = item
                    answer.save()
        elif request.POST.getlist('ansMinArray[]') and request.POST.getlist('ansMaxArray[]'):
            q.min = request.POST.get('minVal')
            q.max = request.POST.get('maxVal')
            q.step = request.POST.get('step')
            q.save()
            minList = request.POST.getlist('ansMinArray[]')
            maxList = request.POST.getlist('ansMaxArray[]')
            if request.POST.getlist('ansAdvicesArray[]'):
                advices = request.POST.getlist('ansAdvicesArray[]')
                zip_min_max_ad = zip(minList, maxList, advices)
                for min, max, ad in zip_min_max_ad:
                    adviceList = str(ad)
                    adviceList = adviceList.split(',')
                    answer = Answer()
                    answer.question = q
                    answer.min_val = min
                    answer.max_val = max
                    answer.save()
                    for item in adviceList:
                        advice = get_object_or_404(Advice, pk=int(item))
                        answer.advices.add(advice)
                        answer.save()
            else:
                zip_min_max = zip(minList, maxList)
                for min, max in zip_min_max:
                    answer = Answer()
                    answer.question = q
                    answer.min_val = min
                    answer.max_val = max
                    answer.save()


        return JsonResponse({'result':'ok'})

src/recsystem/templates/recsystem/add_relation.html
{% extends 'recsystem/default.html' %}
{% block title %}Add Answer{% endblock %}
{% block body %}
    <div class="container">
      <div class="jumbotron relation-div">
          <h3>Add a relation/followup</h3>
          <h4>Select the answer</h4>
          <select class="form-control" name="answer">
            <option value="" >Select Answer</option>
            {% for answer in answers %}
              {% if answer.answer_text %}
              <option value="{{ answer.id }}">{{ answer.answer_text }}</option>
              {% else %}
              <option value="{{ answer.id }}">{{ answer.min_val }}-{{ answer.max_val}}</option>
              {% endif %}
            {% endfor %}
          </select>
          <h4>Select the followup question</h4>
          <select class="form-control" name="question">
            <option value="" >Select Question</option>
            {% for question in questions %}
              <option value="{{ question.id }}">{{ question.question_text }}</option>
            {% endfor %}
          </select>
          <button type="button" class="btn btn-md btn-success" name="button" onclick="submitForm();">Submit</button>
      </div>
    </div>
    <script type="text/javascript">

      var ans,
          que;
          $('select[name=answer]').on('change', function() {
              ans = this.value;
              console.log(ans);
          });
          $('select[name=question]').on('change', function() {
              que = this.value;
              console.log(que);
          });
      function submitForm(){

        $.ajax({
          type: 'POST',
          url: '{% url "recsystem:save_relation" %}',
          data: {
            csrfmiddlewaretoken: "{{ csrf_token }}",
            answer: ans,
            question: que
          },
          success: function(data){
            console.log(data);
            var getUrl = window.location;
            var baseUrl = getUrl .protocol + "//" + getUrl.host + "/" + getUrl.pathname.split('/')[1];
            window.location = baseUrl + '/details';
          },
          error: function(error){
            console.log(error);
          }
        });
      }
    </script>
{% endblock %}

src/recsystem/templates/recsystem/advices.html
{% extends 'recsystem/default.html' %}
{% block body %}
<!-- template for displaying all the advices stored in the database -->
<div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <table class="table table-striped table-bordered table-hover">
          <tr>
            <th>ID</th>
            <th>Advice Label</th>
            <th>Advice Text</th>
            <th>Delete</th>
          </tr>

          {% for advice in advices %}
            <tr>
              <td>{{ advice.id }}</td>
              <td><a href="{% url 'recsystem:editAdvice' advice.id %}">{{ advice.advice_label }}</a></td>
              <td>{{ advice.advice_text }}</td>
              <td><a href="#" class="btn btn-danger btn-xs" onclick="return confirm('Are you sure you want to delete this item?');">
                  <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
              </a></td>
            </tr>
          {% endfor %}
        </table>
      </div>
    </div>
</div>
{% endblock %}

src/recsystem/templates/recsystem/default.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Recommender</title>
  {% load staticfiles %}
  <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'recsystem/button.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'recsystem/main.css' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.0.2/css/bootstrap-slider.css">
  <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.debug.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.0.2/bootstrap-slider.js"></script>
  <script src="{% static 'recsystem/js/jsoneditor/jsoneditor.min.js' %}"></script>
</head>

<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">

      <!-- Header -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'recsystem:index' %}"><img src="{% static 'recsystem/images/logo.png' %}" alt=""></a>
      </div>

      <!-- Items -->
      <div class="collapse navbar-collapse" id="topNavBar">
        <ul class="nav navbar-nav">
          <li class=""><a href="{% url 'recsystem:index' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Recommender</a></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp; Details
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown1">
              <li>
                <a class="dropdown-item" href="{% url 'recsystem:details' %}">
                  <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp; Questions
                </a>
              </li>
              <li role="separator" class="divider"></li>
              <li><a class="dropdown-item" href="{% url 'recsystem:allAdvices' %}">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Advice</a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <a class="dropdown-item" href="{% url 'recsystem:question_form' %}">
                  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Question
                </a>
              </li>
              <li role="separator" class="divider"></li>
              <li><a class="dropdown-item" href="{% url 'recsystem:add_advice' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Advice</a>
              </li>
              <li role="separator" class="divider"></li>
              <li><a class="dropdown-item" href="{% url 'recsystem:add_relation' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add relation</a>
              </li>
            </ul>
          </li>
          <li>
            <a href="{% url 'recsystem:logout_user' %}">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block body %} {% endblock %}
</body>

</html>

src/recsystem/templates/recsystem/default_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Recommender{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'recsystem/main.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- <script src="{% static 'music/js/main.js' %}"></script> -->
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'recsystem:index' %}"><img src="{% static 'recsystem/images/logo.png' %}" alt=""></a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'recsystem:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'recsystem:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

src/recsystem/templates/recsystem/editAdvice.html
{% extends 'recsystem/default.html' %}
{% block title %}Edit Advice{% endblock %}
{% block body %}
<!-- template for editing and updating advices -->
    <div class="container">
          <div class="col-sm-12 col-md-7">
              <div class="panel panel-default">
                  <div class="panel-body jumbotron">
                      <h3>Edit Advice</h3>

                      <form class="form-horizontal" role="form" action="{% url 'recsystem:saveAdvice' advice.id %}" method="post" >
                          {% csrf_token %}
                          <div class="form-group">
                              <div class="col-sm-offset-2 col-sm-10">
                                  <span class="text-danger small"></span>
                              </div>
                              <label for="" class="control-label col-sm-2">
                                <label for="id_advice_label">Advice label:</label>
                              </label>
                              <div class="col-sm-10">
                                <textarea name="advice_label" rows="10" cols="40" maxlength="2000" required id="id_advice_label">{{ advice.advice_label }}</textarea>
                              </div>
                          </div>
                          <div class="form-group">
                              <div class="col-sm-offset-2 col-sm-10">
                                  <span class="text-danger small"></span>
                              </div>
                              <label for="" class="control-label col-sm-2">
                                <label for="id_advice_text">Advice Text:</label>
                              </label>
                              <div class="col-sm-10">
                                <textarea name="advice_text" rows="10" cols="40" maxlength="3000" required id="id_advice_text">{{ advice.advice_text }}</textarea>
                              </div>
                          </div>
                          <div class="form-group">
                              <div class="col-sm-offset-2 col-sm-10">
                                  <span class="text-danger small"></span>
                              </div>
                              <label for="" class="control-label col-sm-2">
                                <label for="id_time_stamp">Time stamp:</label>
                              </label>
                              <div class="col-sm-10">
                                <textarea name="time_stamp" rows="10" cols="40" maxlength="3000" required id="id_time_stamp">{{ advice.time_stamp }}</textarea>
                              </div>
                          </div>
                          <div class="form-group">
                              <div class="col-sm-offset-2 col-sm-10">
                                  <button type="submit" class="btn btn-success">Submit</button>
                              </div>
                          </div>
                      </form>
                  </div>
              </div>
          </div>

    </div>

{% endblock %}

src/recsystem/templates/recsystem/login.html
{% extends 'recsystem/default_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'recsystem:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'recsystem:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

src/recsystem/templates/recsystem/register.html
{% extends 'recsystem/default_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'recsystem/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'recsystem:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}